config/routes.rb
Rails.application.routes.draw do
  devise_for :employees
  devise_for :clients

  resources :order_clients, only: %i[index show] do
    resources :approved_orders, only: %i[create]
    resources :rejected_orders, only: %i[new create]
  end
  root to: 'home#index'
  resources :companies, only: %i[show new create edit update] do
    get 'orders', on: :collection
  end
  namespace :client do
    resources :order_clients, only: %i[index show create] do
      post 'cancel', on: :member
    end
  end
  resources :plans, only: [:index]
  resources :promos, only: %i[index new create] do
    post 'approve', on: :member
  end
end

app/models/approved_order.rb
class ApprovedOrder < ApplicationRecord
  has_one :rejected_order, dependent: :destroy
  has_one :cancel_bot_client, dependent: :destroy
  belongs_to :order_client
end

app/controllers/approved_orders_controller.rb
class ApprovedOrdersController < ApplicationController
  def create
    @order_client = OrderClient.find(params[:order_client_id])
    if ApproveOrder.new(@order_client).call
      redirect_to @order_client, notice: t('.success')
    else
      redirect_to @order_client, alert: t('.fail')
    end
  end
end

app/views/approved_orders/index.html.erb
<div class="table-order-clients">
  <% if @order_clients.empty? %>
  <div class="without-order-clients">
    <div><%= image_tag("empty.svg", size: "300x300", alt: "")%></div>
    <h3>Você ainda não adquiriu um bot ou seu pedido está mediante à aprovação</h3>
  </div>
  <% else %>
     <h2>Lista de Bots</h2>
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col"><%= OrderClient.human_attribute_name(:plan) %></th>
          <th scope="col"><%= OrderClient.human_attribute_name(:token) %> do bot</th>
          <th scope="col"><%= Client.human_attribute_name(:email) %></th>
          <th scope="col">Cancelamento</th>
        </tr>
      </thead>
      <tbody>
          <% @order_clients.each do |order_client| %>            
          <tr>
            <td><%= order_client.approved_order.id %></td>
            <td><%= link_to order_client.plan, approved_order_path(order_client.approved_order) %></td>
            <td><%= order_client.token %></td>
            <td><%= order_client.client.email %></td>
            <% if order_client.approved_order.cancel_bot_client %>
              <td>
                <%= link_to 'Processo de Cancelamento', 
                    approved_order_cancel_bot_client_path(
                    order_client.approved_order, 
                    order_client.approved_order.cancel_bot_client)
                %>
              </td>
            <% else %>
              <td class="link-cancel-order">
                <%= link_to 'Cancelar Bot', new_approved_order_cancel_bot_client_path(order_client.approved_order) %>
              </td>
            <% end %>
          </tr>
          <% end %>
      </tbody>
   </table>   
  <% end %>
</div>

app/views/approved_orders/show.html.erb
<p class="link-back"><i class="fa fa-arrow-left" aria-hidden="true"></i><%= link_to 'Voltar', approved_orders_path %></p>

<section class="container-company">
  <div class="info-company">
    <ul class="list-group">
      <li class="list-group-item list-group-item-dark">
        <strong>Plano:</strong>
	<%= @plan.name %>
      </li>
      <li class="list-group-item list-group-item-action">
        <strong>Token:</strong>
	<%= @approved_order.order_client.token %>
      </li>
      <li class="list-group-item list-group-item-action">
        <strong>Status:</strong>
	<%= OrderClient.human_attribute_name("status.#{@approved_order.order_client.status}") %>
      </li>
      <li class="list-group-item list-group-item-action">
        <strong>Plataformas:</strong>
	<%= @plan.platforms %>
      </li>
      <li class="list-group-item list-group-item-action">
        <strong>Limite diário de mensagens:</strong>
	<%= @plan.limit_daily_messages %>
      </li>
      <li class="list-group-item list-group-item-action">
        <strong>Limite mensal de mensagens:</strong>
	<%= @plan.limit_monthly_messages %>
      </li>
    </ul>
  </div>
  <div>
    <div class="personal_info"><%= image_tag("personal_info.svg", size: "400x400", alt: "")%></div>
  </div>
</section>