config/routes.rb
Rails.application.routes.draw do
  devise_for :employees
  devise_for :clients

  resources :order_clients, only: %i[index show] do
    resources :approved_orders, only: %i[create]
    resources :rejected_orders, only: %i[new create]
  end
  root to: 'home#index'
  resources :companies, only: %i[show new create edit update] do
    get 'orders', on: :collection
  end
  namespace :client do
    resources :order_clients, only: %i[index show create] do
      post 'cancel', on: :member
    end
  end
  resources :plans, only: [:index]
  resources :promos, only: %i[index new create] do
    post 'approve', on: :member
  end
end

app/views/shared/_flashes.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-secondary"-<%= key %>">
    <%= value %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_orders.html.erb
<div class="table-order-clients">
  <% if @order_clients.empty? %>
    <div class="without-order-clients">
      <div><%= image_tag("empty.svg", size: "300x300", alt: "")%></div>
      <% if client_signed_in? %>
        <h3>Você não possui pedidos</h3>
      <% else %>
        <h3>Nenhum pedido cadastrado</h3>
      <% end %>
    </div>
  <% else %>
    <h2>Lista de Pedidos</h2>
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col"><%= OrderClient.human_attribute_name(:token) %></th>
          <th scope="col"><%= OrderClient.human_attribute_name(:plan) %></th>
          <th scope="col"><%= Client.human_attribute_name(:email) %></th>
          <th scope="col"><%= OrderClient.human_attribute_name(:status) %></th>
          <% if client_signed_in? %>
            <th scope="col">#</th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% @order_clients.each do |order| %>
          <tr>
            <th scope="row"><%= order.id %></th>
            <td ><%= link_to order.token, order %></td>
            <td><%= order.plan.name %></td>
            <td><%= order.client.email %></td>
            <% if order.accepted? %>
              <td><strong class="status-accepted">
                <%= OrderClient.human_attribute_name("status.#{order.status}") %>
              </strong></td>
            <% elsif order.rejected? %>
              <td><strong class="status-rejected">
                <%= OrderClient.human_attribute_name("status.#{order.status}") %>
              </strong></td>
            <% else %>
              <td><strong>
                <%= OrderClient.human_attribute_name("status.#{order.status}") %>
              </strong></td>
            <% end %>
            <% if client_signed_in? %>
              <% if order.waiting? %>
                <td class="link-cancel-order"><%= link_to 'Cancelar Pedido', cancel_client_order_client_path(order),
                                id:"cancel-#{order.id}",
                                method: :post  %></td>
              <% else %>
                <td></td>
              <% end %>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>