config/routes.rb
Rails.application.routes.draw do
  devise_for :employees
  devise_for :clients

  resources :order_clients, only: %i[index show] do
    resources :approved_orders, only: %i[create]
    resources :rejected_orders, only: %i[new create]
  end
  root to: 'home#index'
  resources :companies, only: %i[show new create edit update] do
    get 'orders', on: :collection
  end
  namespace :client do
    resources :order_clients, only: %i[index show create] do
      post 'cancel', on: :member
    end
  end
  resources :plans, only: [:index]
  resources :promos, only: %i[index new create] do
    post 'approve', on: :member
  end
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :client

  validates :fantasy_name, :corporate_name, :email, :cnpj,
            uniqueness: true
  validates :fantasy_name, :corporate_name, :email, :cnpj,
            :address, presence: true
  validate :cnpj_validation

  has_secure_token

  after_create_commit :send_company_to_management_system

  private

  def cnpj_validation
    return if CNPJ.valid?(cnpj)

    errors.add(:cnpj, 'CNPJ não é valido')
  end

  def send_company_to_management_system
    ManagementSystem.client.post do |req|
      req.url 'companies'
      req.body = attributes.to_json
    end
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_client!
  before_action :complete_company, only: %i[show edit orders]

  def new
    @company = Company.new
  end

  def create
    company_created_msg = t('company_created', scope: %i[company sessions])
    @company = current_client.build_company(company_params)
    return redirect_to @company, alert: company_created_msg if @company.save

    render 'new'
  end

  def show
    @company = Company.find(params[:id])
  end

  def edit
    @company = Company.find(params[:id])
  end

  def update
    @company = Company.find(params[:id])
    @company.update(company_params)
    if @company.save
      flash[:success] = 'Empresa editada com sucesso'
      redirect_to @company
    else
      render 'edit'
    end
  end

  def orders
    @orders = current_client.order_clients
  end

  private

  def company_params
    params.require(:company).permit(:fantasy_name, :corporate_name,
                                    :email, :cnpj, :address)
  end
end

app/views/companies/_form.html.erb
<div class="form-group company">
  <%= form_for @company, local: true do |f| %>
    <%= f.label :fantasy_name %></label>
    <li class="form-control"><%= f.text_field :fantasy_name %></li><br>
    <%= f.label :corporate_name %>
    <li class="form-control"><%= f.text_field :corporate_name %></li><br>
    <%= f.label :email %>
    <li class="form-control"><%= f.text_field :email %></li><br>
    <%= f.label :cnpj %>
    <li class="form-control"><%= f.text_field :cnpj %></li><br>
    <%= f.label :address %>
    <li class="form-control"><%= f.text_field :address %></li><br>
    <button type="submit" class="btn btn-dark company">Enviar</button>
  <% end %>
</div>

app/views/companies/_headers_errors.html.erb
<div class="text-center company">
    <h1><strong>Minha conta</strong></h1>
</div>

<% @company.errors.full_messages.each do |message| %>
  <div class="alert alert-danger company" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= message %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<p class="link-back"><i class="fa fa-arrow-left" aria-hidden="true"></i><%= link_to 'Voltar', company_path(@company) %></p>

<%= render partial: 'headers_errors' %>

<%= render 'form' %>   

app/views/companies/new.html.erb
<%= render partial: 'headers_errors' %>

<%= render 'form' %>    

app/views/companies/orders.html.erb
<div class='container'>
  <div class='row'>
    <div class='card'>
      <div class='col-sm-5'>
        <% @orders.each do |order| %>
          <div class='card-body'>
            <%= order.plan_id %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class='actions'>
    <br/>
    <%= link_to t('back', scope: %i[company actions]),
        :back, class: 'btn btn-primary' %>
  </div>
</div>

app/views/companies/show.html.erb
<p class="link-back"><i class="fa fa-arrow-left" aria-hidden="true"></i><%= link_to 'Voltar', root_path %></p>

<section class="container-company">
  <div class="info-company">
    <ul class="list-group">
      <li class="list-group-item list-group-item-dark">
        <strong><%= Company.human_attribute_name('fantasy_name') %>:</strong>
	<%= @company.fantasy_name %>
      </li>
      <li class="list-group-item list-group-item-action">
        <strong><%= Company.human_attribute_name('corporate_name') %>:</strong>
	<%= @company.corporate_name %>
      </li>
      <li class="list-group-item list-group-item-action">
        <strong><%= Company.human_attribute_name('email') %>:</strong>
	<%= @company.email %>
      </li>
      <li class="list-group-item list-group-item-action">
	<strong><%= Company.human_attribute_name('document_number') %>:</strong>
	<%= @company.cnpj %>
      </li>
      <li class="list-group-item list-group-item-action">
	<strong><%= Company.human_attribute_name('address') %>:</strong>
	<%= @company.address %>
      </li>
    </ul>
    <p class="btn btn-dark edit"><%= link_to 'Editar', edit_company_path %></p>
  </div>
  <div>
    <div class="personal_info"><%= image_tag("personal_info.svg", size: "400x400", alt: "")%></div>
  </div>
</section>

<% if current_client.from?(@company) %>
  <%= link_to 'Compras', orders_companies_path %>
<% end %>